name: HanaWeapons
version: '1.0-SNAPSHOT'
main: xyz.hanamae.hanaWeapons.HanaWeapons
api-version: '1.21'
authors: [ Hanamae_ ]
commands:
  hw:
    description: HanaWeapons main command
    usage: /hw <command>
    permissions:
      hanaweapons.admin:
        description: Allows access to HanaWeapons admin commands
        default: op
